---
- name: Instalar Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Copiar página personalizada de bienvenida
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: www-data
    group: www-data
    mode: '0644'
  notify: Reiniciar Apache

- name: Asegurar que Apache esté iniciado y habilitado
  service:
    name: apache2
    state: started
    enabled: yes
